services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: http-server
    restart: on-failure
    ports:
      - "2000:2000"
    env_file:
      - ./.env
    volumes:
      - ./logs:/mcp/app/logs
