services:
  mcp-http-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-python-http-server
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - STATLESSL_HTTP=False
    command: ["python", "main.py", "--http"]
    volumes:
      - ./logs:/mcp/logs
      - ./data:/mcp/data

  mcp-stdio-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-python-stdio-server
    restart: on-failure
    env_file:
      - ./.env
    environment:
      - STATLESSL_HTTP=True
    volumes:
      - ./logs:/mcp/logs
      - ./data:/mcp/data
    command: ["python", "main.py"]
